# k3d image import derp:latest -c derp 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my2-flask-app
  labels:
    app: {{ .Values.labels }}
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
      - name: flask-app-container
        image: {{ .Values.image.repository}}:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000