# k3d image import derp:latest -c derp 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  labels:
    app: {{ values.labels }}
spec:
  replicas:  {{ values.replicaCount }}
  selector:
    matchLabels:
      app: {{ values.labels }}
  template:
    metadata:
      labels:
        app: {{ values.labels }}
    spec:
      containers:
      - name: flask-app-container
        image: {{ values.image.repository}}:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000