apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  type: NodePort  # Or ClusterIP, LoadBalancer (depends on your setup)
  selector:
    app: {{ .Values.labels }}
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5000 