name: Eric's Java CI Testing With Gradle
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
        
    - uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: |
          **/build/reports/
          **/build/test-results/